#!/bin/bash

ARGS=""
COUNT=1
for i in $*; do
  if [ $COUNT -gt 0 ]
  then
    ARGS="$ARGS $i"
  fi
done

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
export $(cat $DIR/.env | sed 's/#.*//g' | xargs)

docker run -it --rm \
  --env-file $DIR/.env \
  -v $DATA_PATH:/data \
  -v $CODE_PATH/scripts:/app/scripts \
  -v $CODE_PATH/.env:/app/.env \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --cap-add NET_ADMIN \
  --device /dev/net/tun \
  --sysctl net.ipv6.conf.all.disable_ipv6=0 \
  "$DOCKER_IMAGE" $ARGS
